In [ ]:
#Q1-Get your name and age as input and print it in the form like
#Your name is Hulisi. Your age is 43
name=input('What is your name? ')
age=input('What is your age? ')
print('Your name is '+name+'. Your age is '+age)

What is your name? Muraz
What is your age? 20
Your name is Muraz. Your age is 20

In [ ]:
#Q2-Write a if statement for a given two number is equal or not
a=43
b=54
if(a==b):
  print("equal")
else:
  print("not equal")

not equal

In [ ]:
#Q3-Write a if statement for first number is greater (a), equal or less than second number.(b)
a=43
b=54
if a>b:
  print("a is greater than b")
elif a<b:
  print("a is less than b")
else:
  print("They are equal")

a is less than b

In [ ]:
#Q4- Using for loop, print 1,2,3,4,5
for k in range(1,6):
  print(k)

1
2
3
4
5

In [ ]:
#Q5-Using while loop, print 5,4,3,2,1
k=5
for k in range(5,0,-1):
  print(k)

5
4
3
2
1

In [ ]:
#Q6- Using for loop, print 10,6,4,2,0
#Hint Print if number is not equal to 8.
k=10
for k in range(10,-1,-2):
 if(k!=8):
  print(k)

10
6
4
2
0

In [ ]:
#Q7-Write a method to calculate age for a given date of birth year.
#Use this method on orer to calculate age of person if date of birth is 1944
# if age is the name of function, print(age(1944))
birth_year = int(input("Please tell your birth year: "))
age= 2022-birth_year
print(age)

Please tell your birth year: 1944
78

In [ ]:
#Q8-Write a class named arithmetic with method for calculating addition, substraction, multiplication and division of two numbers.
class arithmetic:
  def addition(x,y):
    return x+y
print(arithmetic.addition(8,5))

class arithmetic:
  def substraction(x,y):
    return x-y
print(arithmetic.substraction(8,5))

class arithmetic:
  def multiplication(x,y):
    return x*y
print(arithmetic.multiplication(8,5))

class arithmetic:
  def division(x,y):
    return x/y
print(arithmetic.division(8,5))

13
3
40
1.6

In [ ]:
#Q9- write a for loop or method  to calculate summation of first n numbers
#i.e if n=3, it will print or return 6 (1+2+3)
finsum=0
n=3
for x in range (1,n+1):
  finsum=finsum+x
print(finsum)

6

In [ ]:
#Q10-Generate 10 numbers between 0 and 1 and add into list. Print first three elements of that list. 
import numpy as np

ls=[]
 
for k in range(0,10):
  ls.append(np.random.rand()*1)

ls[0:3]

[0.48204994333763185, 0.028128920735952745, 0.3953589432100627]

In [ ]:
#Q11-For a given number n, print numbers divisible by 3 up to that number(n included)
#Example: if n=15, print 3,6,9,12,15
#Hint you can use modulus statement (if (i%3==0))
n=15
for n in range (1,n+1):
  if n%3==0:
    print(n)

3
6
9
12
15